//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _2hours
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrderDetail
    {
        public int orderNumber { get; set; }
        public Nullable<System.DateTime> orderDate { get; set; }
        public Nullable<System.TimeSpan> deliveryTime { get; set; }
        public Nullable<int> approvedByAdmin { get; set; }
        public Nullable<int> userID { get; set; }
    
        public virtual UserProfile UserProfile { get; set; }
    }
}
